### ISSUE TITLE
World "corrupt" after wrenching pipe connected to a pump

### ISSUE THREAD

**Issue by Gijsveld** [GregTechCEu/GregTech-Modern-Community-Pack#12]
I've accidentally added an LV pump to a pipe that's connect to a fluid tank. After wrenching the pipe to make it disconnect from the pump the game crashed. Every time I try to load the world now it crashes instantly.

[crash-2024-01-02_12.52.01-server.txt](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/files/13809633/crash-2024-01-02_12.52.01-server.txt)
[crash-2024-01-02_12.53.15-server.txt](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/files/13809634/crash-2024-01-02_12.53.15-server.txt)
[crash-2024-01-02_12.50.42-server.txt](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/files/13809635/crash-2024-01-02_12.50.42-server.txt)

**Comment by ursamina** [comment]
oh dear! could you make this an issue on the GTModern github?

[issues tab here](https://github.com/GregTechCEu/GregTech-Modern/issues)

**Comment by ursamina** [comment]
should be fixed in ceu
