### ISSUE TITLE
The ore generation section of the guide seems to be incorrect.

### ISSUE THREAD

**Issue by tolomea** [GregTechCEu/GregTech-Modern-Community-Pack#14]
I'm new to Gregtech, so don't really know what I'm doing.
Also I have added Terralith and Tectonic, not sure if that matters.

The ore gen section of the guide does not seem to agree with actual game play.

It asserts that veins are on a grid that steps every 3 chunks, meanwhile the scanner thing shows a much more random looking distribution.

It also says veins are always 7 blocks thick, I have one that appears to be about 20 blocks thick.

This isn't a problem per se, I just follow the scanner, but it seemed off so I thought I'd mention it.

Also I've seen references elsewhere that suggest some ores only spawn up high in mountains, is this still the case?

p.s. Game rage 🤣

**Comment by ursamina** [comment]
fixed the quest description to be less "one-size-fits-all", thanks

also some ores will typically spawn higher/lower. sulfur ore veins in the nether can spawn infamously low down under the lava

**Comment by tolomea** [comment]
I'm having a lot of difficulty find substantial copper deposits, is there anything special about the copper related ores
