### ISSUE TITLE
Some Mining Hammers and Axes not preforming as intended

### ISSUE THREAD

**Issue by Sparky1492** [GregTechCEu/GregTech-Modern-Community-Pack#15]
Good Day,

I'm playing GregTech CEu Modern Community Pack 1.20.1 (v. 1.1.1) , Single player Survival.

Mining Hammers and Axes made of Invar, Rose Gold, or Damascus Steel do not operate correctly.

Expected the mining hammers to break a 3x3x1 and the axes to fell the whole tree.

What happens is both tools only break 1 block when made by the player.  If tools are given to the player from JEI they work as intended.

Also, if any of those tools are player made, they only show 4 NBT tags vs the given tools from JEI of 5 NBT tags. (example shown below)

 - Player Made Invar Mining Hammer NBT

`entity data: {id: "gtceu:invar_mining_hammer", Count: 1b, tag: {GT.Tool: {HarvestLevel: 2, ToolSpeed: 5.6f, Damage: 1, MaxDamage: 1152}, GT.Behaviours: {}, Damage: 0, Enchantments: [{lvl: 1s, id: "minecraft:efficiency"}]}}`

 - Player Given Invar Mining Hammer NBT

`entity data: {id: "gtceu:invar_mining_hammer", Count: 1b, tag: {DisallowContainerItem: 0b, GT.Tool: {HarvestLevel: 2, ToolSpeed: 5.6f, Damage: 9, MaxDamage: 1151}, GT.Behaviours: {AoELayer: 0, MaxAoELayer: 0, AoERow: 1, AoEColumn: 1, MaxAoERow: 1, MaxAoEColumn: 1}, HideFlags: 2, Enchantments: [{lvl: 1s, id: "minecraft:efficiency"}]}}`

I've tested also tested this with updated the GregTech CEu Modern mod v.1.0.20 and v.1.20.b-build_401.

I do not see any errors when trying to use the tools.

The only thing I have found so far in common with the two types of tools in those specific materials is the ' tools.js' in th e kubejs server scripts. [https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/blob/main/kubejs/server_scripts/gregtech/tools.js]

Please let me know if there any additional information I can provide or testing I can do.

Thank you all for your work! 👍

**Comment by Sparky1492** [comment]
Also just noticed the Butchery Knife seems to have a similar issue with the enchantments/tags it's suppose to have.

### Player made
![Screenshot from 2024-01-13 11-51-16](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/945772/eb4afd3f-f166-4909-9c3f-b64e4b4a8343)

 - NBT

`entity data: {id: "gtceu:invar_butchery_knife", Count: 1b, tag: {GT.Tool: {HarvestLevel: 2, Damage: 27, MaxDamage: 384}, Damage: 0, Enchantments: [{lvl: 1s, id: "minecraft:unbreaking"}]}}`

-------------------------

### Give to player from JEI
![Screenshot from 2024-01-13 11-51-37](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/945772/f9179062-db0b-4c85-9904-a04d2ea0e388)

 - NBT 

`entity data: {id: "gtceu:invar_butchery_knife", Count: 1b, tag: {DisallowContainerItem: 0b, GT.Tool: {AttackDamage: 4.5f, Damage: 0, MaxDamage: 383, AttackSpeed: -1.3f}, GT.Behaviours: {}, HideFlags: 2, Enchantments: [{lvl: 3s, id: "minecraft:bane_of_arthropods"}, {lvl: 3s, id: "minecraft:looting"}]}}`

**Comment by ursamina** [comment]
fixed in latest
