### ISSUE TITLE
"Lumbering On" quest broken - outdated tag?

### ISSUE THREAD

**Issue by jtuc** [GregTechCEu/GregTech-Modern-Community-Pack#19]
The "Lumbering On" quest appears to no longer work.
The quest requires a `forge:tools/tree_felling` tag, but I think this tag might not exist any more after the tools rework?

https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/blob/ff8a46c8c49c97d25352a4ff12cd95ef00f6e380/config/ftbquests/quests/chapters/gtceu.snbt#L213

This results in the questbook showing a broken "Tasks" icon, and no axes being accepted by the quest.
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/6748724/0f87fb63-48e3-443d-830e-e682af1a2f51)

**Comment by ursamina** [comment]
fixed in latest
