### ISSUE TITLE
Multiblock Preview missing in JEI

### ISSUE THREAD

**Issue by daviddomkar** [GregTechCEu/GregTech-Modern-Community-Pack#24]
I cannot find Multiblock Preview tab in JEI. As a new GregTech player this makes my playtrough a bit rough. Is there any way to fix it? Or did I missed some shortcut to activate it? I am on version 1.3.0.

**Comment by ursamina** [comment]
cant reproduce, press U on a machine to view its tab
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/143211829/2395d865-81b0-4f20-b58d-04fb48370c7d)
