### ISSUE TITLE
Suggestion - Add mod to keep options.txt from getting over written.

### ISSUE THREAD

**Issue by Sparky1492** [GregTechCEu/GregTech-Modern-Community-Pack#26]
Good day,

Would you consider adding a mod to keep the options.txt file from getting over written every update?

I've found "Default Options" on Curseforge that should do this.  It required "Balm" which you already have to "Crafting Tweaks" by BlayTheNinth.  
The current version of "Balm" the pack has is v. 7.2.1 and the most current version out is 9.0.5, so I don't know if that would create any issues.

[Default Options](https://www.curseforge.com/minecraft/mc-mods/default-options)

[Balm](https://www.curseforge.com/minecraft/mc-mods/balm)

Please let me know if you need any additional information or have any questions.

Thank you,
Sparky1492

**Comment by ursamina** [comment]
new in latest
