### ISSUE TITLE
Large miners do not produce 3x more crushed ore than a macerator

### ISSUE THREAD

**Issue by JoshX9706** [GregTechCEu/GregTech-Modern-Community-Pack#28]
In the large miner tooltip, it says "produces 3x more crushed ore than a macerator" but in tests, it produced:
44 crushed magnetite ore from 9 magnetite ore; 4.9 crushed ore on average
35 crushed molybdenum ore from 9 end molybdenum ore; 3.9 crushed ore on average
these rates are abysmal, and even below the rates a normal macerator gives and a far cry from the advertised "6 crushed ore per normal ore" and "12 crushed ore per nether/end ore"
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/47550807/1d07f030-fb0f-4a86-b500-2a4c0bb5fb5d)

**Comment by ursamina** [comment]
sounds like a ceu issue - you might want to discuss this on their repo/their discord
