### ISSUE TITLE
Broken quest reward

### ISSUE THREAD

**Issue by koh-gh** [GregTechCEu/GregTech-Modern-Community-Pack#29]
"LV Electric Piston" quest is broken. The correct tag is "small_steel_gear". Maybe changed in GTCEu Modern?
![2024-02-11_12 36 09](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/36918206/fde072f8-73a2-4f74-ad10-98e320fe75f2)
![2024-02-11_12 36 21](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/36918206/9a68646c-cc3b-4a4e-80c9-560a96f28c41)

**Comment by ursamina** [comment]
fixed
