### ISSUE TITLE
[1.7.0]Axe in task reward doesn't vein mine.

### ISSUE THREAD

**Issue by 9-Extra** [GregTechCEu/GregTech-Modern-Community-Pack#39]
The axe from the task "A minor Test of Strength" on the chapter "Introduce" does't do vein mine after break a wood on the tree while the handmade ones can. It works just like the vanllin verison which only speed up breaking but can't vein mine.

**Comment by Alves24** [comment]
Do you try latest versions? I think that is fixed

**Comment by ursamina** [comment]
should be fixed
