### ISSUE TITLE
Charcoal with furnace?

### ISSUE THREAD

**Issue by DoneTCT** [GregTechCEu/GregTech-Modern-Community-Pack#40]
i can smelt wood to get charcoal, even though the questbook clearly says i can't.
downloaded from curseforge, tried to update the pack with the zip from git.
![Untitled](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/48444041/72421945-e88d-48d4-b255-10f951c4e4c7)

**Comment by ursamina** [comment]
fixed
