### ISSUE TITLE
[BUG] "Xtone Tile" block not recoverable

### ISSUE THREAD

**Issue by Alves24** [GregTechCEu/GregTech-Modern-Community-Pack#41]
"Xtone Tile" block not recoverable with pickaxe or any other tool

![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/59389968/2c41dd29-0d90-464c-ac02-74e0959ad4f7)

**Comment by ursamina** [comment]
xtones bug, not a pack problem
