### ISSUE TITLE
[BUG] Inventory profiles interface

### ISSUE THREAD

**Issue by Alves24** [GregTechCEu/GregTech-Modern-Community-Pack#42]
This mod doesn't integrates well with ae2 GUIs
Idk if there is way to disable the interaction with ae2, no sense there.

Solved removing the mod by the moment
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/59389968/a4cbb750-549d-49be-bffe-52df168a129d)

**Comment by ursamina** [comment]
fixed
