### ISSUE TITLE
Chainsaw and Treecapitator Question

### ISSUE THREAD

**Issue by DoneTCT** [GregTechCEu/GregTech-Modern-Community-Pack#44]
The chainsaw from gregtech, when cutting down trees, uses it's durability for all the blocks
and only energy to break the first block is consumed.
Is it working as intended? or should work as the drill (when drilling it uses energy and some durability)?
before cutting my tree clump
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/48444041/d53e4a5b-b656-403e-8105-65151a52720f)
after cutting my tree clump
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/48444041/491ccd08-a06d-406c-b96f-7a8760837733)

**Comment by ursamina** [comment]
issues like this are better suited for the ceu modern repo 

https://github.com/GregTechCEu/GregTech-Modern/issues

with that being said, that doesn't sound like intended behaviour but i can't comment with certainty

**Comment by DoneTCT** [comment]
i saw this bug already fixed 2 weeks ago in the other repo you linked to me, is this gonna be updated in this version of the pack too?
