### ISSUE TITLE
bug on ME interface in version 1.7.1

### ISSUE THREAD

**Issue by flamingkimchi** [GregTechCEu/GregTech-Modern-Community-Pack#47]
previously, fluid could be extracted through  storage bus without the need to set ME interface. but in version 1.7.1, combo with storage bus can only be done if it is set.
[![Video Label](http://img.youtube.com/vi/3l7OQcPb2b4/0.jpg)](https://youtu.be/3l7OQcPb2b4)

**Comment by ursamina** [comment]
gcp doesnt touch anything related to this
