### ISSUE TITLE
Recipe issues

### ISSUE THREAD

**Issue by Luminance69** [GregTechCEu/GregTech-Modern-Community-Pack#48]
There's a couple recipes I've come accross that overlap:
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/50186248/f01204ab-addd-4c53-b50d-eb646c998bb2)
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/50186248/cddf2c19-1876-43fe-805a-2eb7e037b842)

**Comment by ursamina** [comment]
gtceu bug - the coarse dirt recipe also seems to be fixed on latest ceu
