### ISSUE TITLE
[Feature Request] Jetpack quests

### ISSUE THREAD

**Issue by norwayman22** [GregTechCEu/GregTech-Modern-Community-Pack#49]
From what I know, there are are three jetpacks in gtceum right now:

- Liquid Fuel Jetpack (LV tier)
- Electric Jetpack (MV tier)
- Advanced Electric Jetpack (late HV tier)

Right now only the Advanced Electric Jetpack is part of the quest system, as an ingredient in the Advanced NanoMuscle Suite Chestplate quest in the early part of the EV tree.

I think the jetpacks deserve some more love, since you can already get access to one in LV. By the time you get to the quest in EV, you will have missed out on two tiers of jetpacks.

What I would like to see added is at the minimum a quest for the Liquid Fuel Jetpack in the LV tree that mentions the other jetpacks and foreshadows the previously mentioned quest in the EV tree. I think it would provide some nice motivation for players to set a goal to reach the Advanced NanoMuscle armor.

There could also be a quest for the Electric Jetpack which can be a dependency for the EV quest, since you need it for the crafting recipe anyways. Though I don't know how well it would fit, since the upgrade might not be worth it on its own, relative to the Liquid Fuel Jetpack.

**Comment by ursamina** [comment]
will add in latest - this is a thing in the 1.12 community pack that should now be ported with the addition of jetpacks to 1.12

thanks a lot!
