### ISSUE TITLE
Quest "Onwards to the Age of Bronze" is improperly formatted

### ISSUE THREAD

**Issue by Lord-Cryptid** [GregTechCEu/GregTech-Modern-Community-Pack#5]
The quest mentioned in the title is currently formatted such that you need both 32 copper and 32 tin to complete the quest, this goes against the text of the quest and defeats the purpose of the reward. 

To fix the quest all that needs to be changed is that instead of the requirements being for both 32 copper and 32 tin ingots, it instead is one requirement of an OR filter item containing both a copper and tin ingot. I've tested this in my own world and it works as intended with the fix.

I apologize for lack of proper formatting, I haven't used github for reporting an issue before now.

**Comment by ursamina** [comment]
fixed in incoming update, thanks
