### ISSUE TITLE
Soladite and Lazulite dont work as lapis substitutes for enchanting

### ISSUE THREAD

**Issue by collosiskdway** [GregTechCEu/GregTech-Modern-Community-Pack#50]
In the quest for lapis ore, it says that soladite and lazulite work as substitutes for lapis when enchanting. this however, is not possible as neither of them in any form can be placed into the lapis slot in the enchantment table. Please let me know if i need to provide any further information for figuring out why that is.

**Comment by ursamina** [comment]
sounds like a ceu parity issue - feel free to report it on their repo if it's still a problem on latest
