### ISSUE TITLE
feat: Ad Astra integration

### ISSUE THREAD

**Issue by edshPC** [GregTechCEu/GregTech-Modern-Community-Pack#51]
My suggestion is to add the Ad Astra mod.

The idea is to implement GTNH-like ore generation, where to unlock new type of ore and material, you need to visit specific planet

For example:
* Aluminum vein, needed for MV, will no longer spawned in overworld(or the end), but is now spawned on moon (and higher-tier planets). To get aluminum you need to build a 1 tier rocket with steel and some electronics from LV-tier
* Then, on Mars chrome-containing ores are now spawned, needed for HV, you need to build a tier 2 rocket with steel, desh and MV-elecronics

gtceu has configurable ore gen by kube.js, so I believe it can be implemented

(Ad Astra ores like desh can be also gregoryfied material, and spawns in gt-veins)

**Comment by ursamina** [comment]
this is beyond the intended purpose/scope of the pack as a tutorial pack to help players learn gtceu, sorry
