### ISSUE TITLE
Suggestion: Add covers and facades for GT Pipes and ME cables

### ISSUE THREAD

**Issue by simon12mm** [GregTechCEu/GregTech-Modern-Community-Pack#56]
Title says it all, i just wish for support for covers to the pipes.

**Comment by ursamina** [comment]
this is already possible in ceu + ae2

gt facades:
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/143211829/9582c893-0704-416b-a3c9-55eec562b4de)

ae2:
![image](https://github.com/GregTechCEu/GregTech-Modern-Community-Pack/assets/143211829/d15eccde-d9e2-4173-a3cd-df75efadd228)

if this is an issue then i'll add a quest

**Comment by simon12mm** [comment]
Yeah, this is my first time ever not seeing the recipes in JEI, and while it's nice not to have the clutter, i still didn't realize that you could make AE2 facades at all, or GT facades out of anything but stone. Call it redundant but i do suggest adding a side quest pointing out how to craft them. I got it now though, thanks.

**Comment by simon12mm** [comment]
I believe this issue can be considered resolved, so I'll close it.
