### ISSUE TITLE
Downgrade embeddium to 0.3.19 to allow oculus

### ISSUE THREAD

**Issue by BirbIrl** [GregTechCEu/GregTech-Modern-Community-Pack#58]
Oculus is a must nowadays and most people, upon seeing it's not in the pack - instinctively try to install it only to be met with an illegible mixin error log. I suggest downgrading embeddium to 0.3.19 which no longer has the shimmer+oculus incompatibility

Cheers :>

**Comment by ursamina** [comment]
downgraded in latest
