### ISSUE TITLE
Why does the advanced fluid drilling rig not work with MV?

### ISSUE THREAD

**Issue by Jiofef** [GregTechCEu/GregTech-Modern-Community-Pack#70]
The description says that it works on MV and HV, as well as its creation is in the MV quest branch
![Снимок экрана (329)](https://github.com/user-attachments/assets/722cdbcb-dc8e-44c8-8858-7c92c43ca4d8)
![Снимок экрана (331)](https://github.com/user-attachments/assets/7ae69a10-d7c0-4b9e-af17-1cde54fff343)
![Снимок экрана (332)](https://github.com/user-attachments/assets/030eb1e0-6fc3-42f1-8310-f303df6f3574)

**Comment by ursamina** [comment]
this should work - if still not, please make an issue on the ceu github. this is for issues specific to GCP. ty for the issue nonetheless
