### ISSUE TITLE
Distillation tower doesn't work unless all fluids can be outputted, aka it needs to be the full 13 blocks tall to work with most recipes.

### ISSUE THREAD

**Issue by InkstainTheBat** [GregTechCEu/GregTech-Modern-Community-Pack#71]
I'm guessing this is a bug as the quest book states that you can deliberately make the DT shorter, which would void the fluids that cannot be produced, however, instead, the DT simply doesn't activate.

Edit: this appears to be an issue with Gregtech, as testing it alone on a separate instance the same thing happens

**Comment by ursamina** [comment]
yea, issue with GT - i know this feature is being worked on indev, so look forward to it eventually :)
