### ISSUE TITLE
start.sh script for server files throws invalid hash error

### ISSUE THREAD

**Issue by yvessommer** [GregTechCEu/GregTech-Modern-Community-Pack#73]
steps to make the error occur

environment:
fresh Debian 12

commands:
sudo apt-get update
sudo apt install default-jdk
bash start.sh

![image](https://github.com/user-attachments/assets/6a9c871e-6718-4b79-8eff-83e9f31db5db)

**Comment by ursamina** [comment]
uhh. shit. does this still happen? i refreshed the hashes. ):
