### ISSUE TITLE
Flint Dust not crafting down

### ISSUE THREAD

**Issue by LukeSchmidtler** [GregTechCEu/GregTech-Modern-Community-Pack#74]
Going through the glass quest, it requires the maceration of flint which you then make into smaller dusts in the crafting grid. The flint dust to smaller flint dusts don't  work. Tried in a new creative world and after a restart.

**Comment by ursamina** [comment]
This is a shaped recipe so you need to place the dust in the correct slot in the crafting table

I guess it's confusing to some people so I'll add an addendum in the questbook

**Comment by LukeSchmidtler** [comment]
I guess I never put it in a crafting table, only the inventory. 

Thank you!
