### ISSUE TITLE
GregTech crates can neither be sorted nor interact with the Crafting Station

### ISSUE THREAD

**Issue by aGreasedPig** [GregTechCEu/GregTech-Modern-Community-Pack#75]
As the title already explains, the crate can not be sorted by middle-clicking or shows up as an inventory when attached to a crafting station

**Comment by ursamina** [comment]
could you make an issue/feature request on the main GTCEu modern repo? thanks - this isn't quite related to the internals of the pack but more so likely due to the internals of GTCEu. feel free to reopen if you disagree/know of a way for me to easily fix this however

**Comment by aGreasedPig** [comment]
Happy to do so. You might, however, want to reflect this limitation in the quest relating to the GTCEu Crates and maybe even hint at larger storage solutions (e.g. Sophisticated Storage, Iron Chests) that work in this manner to dissapointment.

**Comment by ursamina** [comment]
added to the list ^ thanks
