### ISSUE TITLE
Quest "US Simulator" assumes "Oil" instead of "Raw Oil" + pumps are bugged

### ISSUE THREAD

**Issue by Lekrashar** [GregTechCEu/GregTech-Modern-Community-Pack#79]
In this current version (gtceu-1.20.1-1.4.4), oil spouts provide "Raw Oil" but the quest assumes they provide "Oil" instead.
Two consequences:
- Oil buckets cannot be obtained until you get a rig. Gatekeeping the quest
- The quest tells you to distill Oil into Sulfuric Light Fuel. But since Raw Oil is provided instead, Sulfuric Naphtha may be way more efficient (unless you crave badly for diesel, although I didn't run any calculations for diesel specifically)

I haven't found any plans, issues nor PR that'll change oil spouts to provide "Oil" instead of "Raw Oil". Therefore I'd suggest changing the quest requirement and text to fix the aforementioned issues.

---
Indirectly related and more of a heads up: Pumps are bugged.
[By the looks of it](https://github.com/GregTechCEu/GregTech-Modern/pull/2003), this might get fixed in 1.4.5 or the version right after, hopefully.

IMO, this one doesn't warrant a quest update or an issue here; since there is a PR that has been approved at this point. But I'm mentioning it, just in case.

**Comment by ursamina** [comment]
fixed in latest
