### ISSUE TITLE
Large Steam Boiler GUI broke on update 1.11.2

### ISSUE THREAD

**Issue by LukeSchmidtler** [GregTechCEu/GregTech-Modern-Community-Pack#80]
All large steam boiler GUI's are not working or showing any info in update 1.11.2. 

The GUI works in update 1.11.1, so I have rolled back for now.

**Comment by ursamina** [comment]
does this work on hotfix 1.11.3? ty for the issue

**Comment by LukeSchmidtler** [comment]
Still broken on 1.11.3

**Comment by ursamina** [comment]
could you make an issue for this on the [GTModern repository](https://github.com/GregTechCEu/GregTech-Modern/issues)?

**Comment by ursamina** [comment]
hopefully fixed in 1.5
