### ISSUE TITLE
Cannot enter my server due to an error lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.gregtechceu.gtceu.api.recipe.ingredient.FluidContainerIngredient@a57e7d1

### ISSUE THREAD

**Issue by ujifffy** [GregTechCEu/GregTech-Modern-Community-Pack#81]
ujify lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.gregtechceu.gtceu.api.recipe.ingredient.FluidContainerIngredient@a57e7d1

**Comment by madman404** [comment]
Having the same issue myself as of the server's last restart:
lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.gregtechceu.gtceu.api.recipe.ingredient.FluidContainerIngredient@5c69cac4

**Comment by ursamina** [comment]
@ both - i just pushed an update to cf with the gt modern hotfix. could you both confirm if this still occurs (it shouldn't anymore!)?

**Comment by Clarkery** [comment]
I had this issue when the 1.4.5 update initialy was pushed and the 1.4.6 hotfix did fix the issue for me. This issue can likely be closed 👍 .

**Comment by ursamina** [comment]
brilliant to hear
