### ISSUE TITLE
1.5.0 Crashes server

### ISSUE THREAD

**Issue by MefistoFereasy** [GregTechCEu/GregTech-Modern-Community-Pack#83]
[crash-2024-11-14_00.16.12-fml.txt](https://github.com/user-attachments/files/17739385/crash-2024-11-14_00.16.12-fml.txt)
[latest.log](https://github.com/user-attachments/files/17739386/latest.log)

**Comment by shal0l** [comment]
Fixed https://github.com/GregTechCEu/GregTech-Modern/issues/2329

**Comment by ursamina** [comment]
gt1.5 issue, will be fixed in next pack update
