### ISSUE TITLE
[Parity] Distilled Water Recipe for Fluix Crystals

### ISSUE THREAD

**Issue by Kawapatch** [GregTechCEu/GregTech-Modern-Community-Pack#89]
Hi Mina!

Just wanted to suggest an alternative recipe for fluix crystals in the autoclave. Right now there's only one for plain water but it'd be great to have one with distilled water as well. As far as I can tell this is the only autoclave recipe that has plain water as its *only* option, so it'd be great to have some parity between it all. 

Thanks,
Kawapatch

![image](https://github.com/user-attachments/assets/bf5e572e-7e3c-470d-9b3f-45c7ab09e1a1)

**Comment by ursamina** [comment]
Will add, thanks for the report

**Comment by ursamina** [comment]
added in latest
