### ISSUE TITLE
Ore generation nerfed (unintentionally?) in 1.0.2 for MC1.20

### ISSUE THREAD

**Issue by CarlSmotricz** [GregTechCEu/GregTech-Modern-Community-Pack#9]
The quest description asserts that ore generation is on a regular grid where chunk=3n+1. This was the case in the MC1.12 version but no longer - ores are still spaced apart, but randomly, and no longer always centered around a middle chunk. Now, with bad luck, it's possible to excavate a whole chunk pillar right under the indicators and find not a single ore.

Mining was grindy in the 1.12 version but this change makes it (IMO) intolerable in the 1.120 version.

If that's intended, OK, but then the description in the quest book should be updated.

**Comment by ursamina** [comment]
not a proper fix but because of the difference in ore generation, you'll now get a LV prospector in v1.1.0 that should carry you far enough to the point at which you can charge it. will keep issue open in case things still aren't tolerable
